# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DirectedGUI import Ui_MainDirWindow


class Ui_MainWindow(object):
    def openDirectedWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainDirWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 156)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dirPushBut = QtWidgets.QPushButton(self.centralwidget)
        self.dirPushBut.setGeometry(QtCore.QRect(140, 80, 141, 28))
        self.dirPushBut.setObjectName("dirPushBut")

        self.dirPushBut.clicked.connect(self.openDirectedWindow)
        
        self.undirPushBut = QtWidgets.QPushButton(self.centralwidget)
        self.undirPushBut.setGeometry(QtCore.QRect(510, 80, 141, 28))
        self.undirPushBut.setObjectName("undirPushBut")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 451, 31))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 10, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AI Search Project"))
        self.dirPushBut.setText(_translate("MainWindow", "Directed Graph"))
        self.undirPushBut.setText(_translate("MainWindow", "Undirected Graph"))
        self.label.setText(_translate("MainWindow", "Choose the type of Graph you want to work on"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Anthony Amgad Fayek : 19P9880</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Youssef George Fouad : 19P9824</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Mostafa Nasrat Metwally : 19P4619</span></p><p><span style=\" font-size:11pt; font-weight:600;\">Kerollos Wageeh Youssef : 19P3468</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Hover Over Me!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
